### ISSUE TITLE
Question: Edit existing Theme Plugin

### ISSUE THREAD

**Issue by LostKatana** [dneustadt/DneTemplateManager#1]
First of all, thanks!
I hated it to navigate through folders on console to just edit a small detail. Make it much easier.

I have made some small adjustments in the default theme via custom theme plugin (I needed to center some pictures)
This plugin only shows the base theme (Storefront) and is not able to handle any changes made in the custom theme plugin, is that right?

If so I can use this as a lookup for the original templates but any changes made to will be overriden with the custom theme plugin.
Is that correct or do I miss something?

Currently the structure is:
Default Storefront -> My Custom Theme

And what I'd like to have is:
Default Storefront -> My Custom Theme -> This Editor

Cheers

**Comment by dneustadt** [comment]
Hey,
all changes to the template introduced by other plugins or themes will still be applied. This plugin doesn't interfere with that behaviour in any way. The preview of the default storefront templates is purely meant as a helpful reference to look up existing blocks, variables e.g. There are currently no plans to display any custom template extensions made outside of the plugin since it would be fairly difficult and it is to be expected that templates will always be based on the structure of the default storefront. So for now you will just have to keep in mind any changes that were made outside this plugin, but they absolutely should still take effect, even if not displayed in the preview window of the plugin UI. 

The order of template inheritance when appending/prepending a single block should be like this in your case:
Default Storefront => Defines Block
Your Custom Theme => Appends/Prepends defined block
Custom Template Manager => Appends/Prepends already altered block of your custom theme

Hope this answers your question.

**Comment by LostKatana** [comment]
Thanks for this awesome fast answer.

Still need to learn a lot here and my mistake was to add the surrounding block element by accident as well.
This caused the edited block from my theme to be overriden by the one I changed in the TemplatManager.

👍  Thanks

**Comment by LostKatana** [comment]
I need to get back to this. Sorry.
Today I tried changing the footers Copyright icon from shopware to something else.
As I already have changed some part here in my theme the changes made in the editor do not get reflected to the page.

The setup is like this:

MyThemes footer.html.twig:
```
{% sw_extends '@Storefront/storefront/layout/footer/footer.html.twig' %}

{% block layout_footer_vat %}
    <div class="footer-vat">
        <p>
            {{ "footer.noVat"|trans({
                '%url%': path('frontend.cms.page',{ id: shopware.config.core.basicInformation.shippingPaymentInfoPage })
            })|raw }}
        </p>
    </div>
{% endblock %}

{% block layout_footer_copyright %}
    <div class="footer-copyright">
        {% sw_icon 'hourglass' style {'size':'xs'} %}
        {{ "footer.copyrightInfo"|trans|sw_sanitize }}
    </div>
{% endblock %}
```

The file in the editor:
```
{% sw_extends '@Storefront/storefront/layout/footer/footer.html.twig' %}

{% block layout_footer_navigation_hotline %}
{% endblock %}

{% block layout_footer_vat %}
    <div class="footer-vat">
        <p>
            {{ "footer.noVat"|trans({
                '%url%': path('frontend.cms.page',{ id: shopware.config.core.basicInformation.shippingPaymentInfoPage })
            })|raw }}
		</p>
    </div>
{% endblock %}

{% block layout_footer_copyright %}
    <div class="footer-copyright">
        {{ "footer.copyrightInfoPre"|trans|sw_sanitize }}
        {% sw_icon 'heart' style {'size':'xs'} %}
        {{ "footer.copyrightInfoAfter"|trans|sw_sanitize }}
    </div>
{% endblock %}
```

The resulting twig tree shows me like this:
```
@Storefront/storefront/base.html.twig::block(base_footer) 11.02ms/5%
└ @Storefront/storefront/base.html.twig::block(base_footer_inner) 11.01ms/5%
  └ @MyTheme/storefront/layout/footer/footer.html.twig 9.57ms/4%
    └ @DneTemplateManager/storefront/layout/footer/footer.html.twig 7.95ms/3%
      └ @Storefront/storefront/layout/footer/footer.html.twig 3.29ms/1%
        └ @Storefront/storefront/layout/footer/footer.html.twig::block(layout_footer_inner_container) 3.26ms/1%
          └ @Storefront/storefront/layout/footer/footer.html.twig::block(layout_footer_bottom) 1.13ms/0%
            └ @Storefront/storefront/layout/footer/footer.html.twig::block(layout_footer_service_menu)
            └ @MyTheme/storefront/layout/footer/footer.html.twig::block(layout_footer_copyright)
              └ @Storefront/storefront/utilities/icon.html.twig
                └ @Storefront/storefront/utilities/icon.html.twig::block(utilities_icon)
 ```
I also tried setting the sw_extends to `{% sw_extends '@Storefront/storefront/layout/footer/footer.html.twig' %}`
Do I miss something?

**Comment by dneustadt** [comment]
Sorry for the late response. Looking at the stack it looks like MyTheme takes precedence over the templates registered by DneTemplateManager. Hence why the changes introduced by the plugin get promptly overwritten by MyTheme. In most cases that would actually be preferable. Let's say you install a payment plugin, that introduces new templates. That's when you would want your theme to takes precedence so you can alter the templates registered by the plugin. I would say DneTemplateManager is mostly targeted at people that don't feel comfortable creating their own themes and/or just want to make minor changes to the default storefront. However there is the possibility to configure your theme to load templates in a specific order. In this case you would want `@MyTheme` **before** `@Plugins` so Plugins may inherit templates from your theme and not the other way round.
Please see: https://docs.shopware.com/en/shopware-platform-dev-en/theme-guide/configuration?category=shopware-platform-dev-en/theme-guide#theme-template-inheritance
