### ISSUE TITLE
Extending document templates has no effect

### ISSUE THREAD

**Issue by DanielPa** [dneustadt/DneTemplateManager#11]
Presumably since we updated form shopware 6.4.18 to 6.4.20 all our custom templates for document are not having any effect.
Templates for pages work as usual and also new changes take effect. 

What I have tried in base.html.twig:

Override 
```twig
{% sw_extends '@Framework/documents/base.html.twig' %}

{% block document_body %}
  <h1>Test</h1>
{% endblock %}
```

Extend 
```twig
{% sw_extends '@Framework/documents/base.html.twig' %}

{% block my_not_existing_block %}
  <h1>Test</h1>
{% endblock %}
```

Override block from includes folder in base.html.twig
```twig
{% sw_extends '@Framework/documents/base.html.twig' %}

{% block document_sender_address %}
  <h1>Test</h1>
{% endblock %}
```

**Comment by dneustadt** [comment]
This is an issue within the Shopware core and template extensions of documents in general. See https://github.com/dneustadt/DneTemplateManager/issues/8.  Should be fixed with Shopware 6.5.
