### ISSUE TITLE
Version v6.3.5.2

### ISSUE THREAD

**Issue by T3chTobi** [dneustadt/DneTemplateManager#2]
Hallo!

Vielen Dank für das tolle Plugin. Mein Shop ist auf der Shopware Version v6.3.5.2, leider unterstützt das Plugin nur die Version v6.3.5.1. Ist es möglich, das Plugin für diese kleine Version freizuschalten?

Vielen Dank!

**Comment by dneustadt** [comment]
Danke für den Hinweis. Ist erledigt.
