### ISSUE TITLE
No menu entry since 6.4.10 anymore

### ISSUE THREAD

**Issue by JensB74** [dneustadt/DneTemplateManager#7]
Hi, and thank you for the great Plugin!

I know, there is no support, but perhaps you have a small peace of time to help ;)

After an update from Shopware 6.4.9 to 6.4.10 the Custom Template menu entry is gone and I don't know how to call the right URL.

I've deactivated the plugin, logged out and in, but the menu entry doesn't come back anymore .. any suggestions? Should I uninstall it and install it again?

Thanks in advance!

**Comment by misterboe** [comment]
Same here

**Comment by Orgoth** [comment]
@dneustadt thank you for testing, after I updated shopware to 6.4.15.1 right now, the menu item reappeared.
